### ISSUE TITLE
can't import {utils} from 'game'

### ISSUE THREAD

**Issue by neuroaktivo** [screepers/typed-screeps-arena#19]
Can't:
`import {utils} from 'game';`

Cause on node_modules/@types/screeps-arena/dist/game/index.d.ts there's this line:
`export * from "game/utils";`

instead of this:
`export * as utils from "game/utils";`

**Comment by thmsndk** [comment]
I am relatively sure that `utils` are not exported in game? I can't seem to find it in the docs at least. it might still exist as a remnant of early alpha.

**Comment by neuroaktivo** [comment]
utils is the same as constants and prototypes... namespaces, right?

What i do(and did while the code was JS) is import constants and then use constants.CONSTANT and the same for prototypes, and utils, that way its clear it comes from the screeps API.

so i do:
` import {utils} from 'game'; /*...*/ utils.getTicks()`
instead of:
 `import {getTicks} from 'game/utils'; /*...*/ getTicks()`

**Comment by thmsndk** [comment]
We can add `export * as utils from "game/utils";` in `game/index.d.ts`, as far as I understand from you it is currently exported in the game?
keep in mind it might change in the future. and that export might be removed, the api is still under development.

The reason for `export * from "game/utils";` is because all the utils where exported in `game` at some point in the alpha, would you mind checking if for example `getTicks` can be imported from `game`?

A PR with the change would also be appreciated  :)

**Comment by neuroaktivo** [comment]
getTicks is in utils even according to official arena documentation.

![image](https://user-images.githubusercontent.com/18504238/164487208-5f1feaf0-3e83-4af1-97fb-08541e075ab3.png)
This is if i try to import it from game. Never have done a PR, but i can try maybe later today.

**Comment by Derpius** [comment]
Importing `utils` from `game` is not only supported but present in the tutorial:  

![image](https://user-images.githubusercontent.com/49565664/167475798-5aee1876-f264-4527-9e76-6e751a10714b.png)
